// FE/src/components/admin/AdPoliCreate.jsx

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Info, Loader2 } from "lucide-react"; // Import Loader2
import axios from "axios";
import useAuth from "@/hook/useAuth";

// API Endpoint for creating a new policy
const POLICIES_API_URL = "/api/policies";

/**
 * @function formatNumber
 * @param {number|string} num - The number value to format.
 * @returns {string} The formatted number string (e.g., "4,000,000").
 */
const formatNumber = (num) => {
  if (!num || isNaN(Number(num))) return "";
  // Using "en-US" locale for comma separation
  return Number(num).toLocaleString("en-US");
};

const INITIAL_FORM_DATA = {
  policyName: "",
  availableYear: "",
  kilometer: "",
};

/**
 * @component
 * @description Form component for creating a new Policy for a specific Part.
 * @param {string} initialPartId - The ID of the part the policy belongs to.
 * @param {function} onSubmit - Handler to submit the new policy data.
 * @param {function} onCancel - Handler to close the modal.
 */
export default function CreatePolicyForm({
  initialPartId,
  onSubmit,
  onCancel,
}) {
  const { auth } = useAuth();

  const [formData, setFormData] = useState(INITIAL_FORM_DATA);
  const [formattedKilometer, setFormattedKilometer] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  // Optional: Add local error state if you don't delegate all errors to the parent
  // const [error, setError] = useState(null);

  // ============= 1. FORM HANDLERS =============

  /**
   * @function handleChange
   * @param {string} field - The key of the field to update.
   * @param {*} value - The new value for the field.
   * @description Generic handler to update form data state.
   */
  const handleChange = (field, value) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  /**
   * @function handleKilometerChange
   * @param {Object} e - Event object from the input field.
   * @description Handles input for the Kilometer field, formats the display value,
   * and saves the raw numeric string to formData.
   */
  const handleKilometerChange = (e) => {
    const inputStr = e.target.value;
    const rawNumberStr = inputStr.replace(/[^0-9]/g, "");
    const numericValue = rawNumberStr ? parseInt(rawNumberStr, 10) : "";

    // 1. Save raw numeric string to formData for API payload
    handleChange("kilometer", String(numericValue));
    // 2. Save formatted value for display
    setFormattedKilometer(formatNumber(numericValue));
  };

  /**
   * @function handleSubmit
   * @description Validates the form, converts necessary fields to numbers, and calls the parent onSubmit handler.
   */
  const handleSubmit = async () => {
    if (
      !initialPartId ||
      !(formData.policyName && formData.availableYear && formData.kilometer)
    ) {
      alert("Please fill in all required fields.");
      return;
    }

    // Basic numerical validation check
    if (
      Number(formData.availableYear) <= 0 ||
      Number(formData.kilometer) <= 0
    ) {
      alert("Available Year and Kilometer must be greater than zero.");
      return;
    }

    setIsSubmitting(true);

    const policyDataToSend = {
      // policyId is generated by the API
      policyName: formData.policyName,
      availableYear: Number(formData.availableYear),
      kilometer: Number(formData.kilometer),
      isEnable: false, // Default: New policy is Inactive
      partId: initialPartId,
    };

    try {
      // Note: Submitting to parent which handles the actual API call
      await onSubmit(policyDataToSend);

      // Reset form on success (assuming parent handles closing modal)
      setFormData(INITIAL_FORM_DATA);
      setFormattedKilometer("");
    } catch (error) {
      // Error handling is primarily delegated to the parent component (AdminPartsPolicy.jsx)
      // but we throw to ensure the finally block runs and Submission state is reset.
      console.error("Policy creation failed:", error);
    } finally {
      setIsSubmitting(false);
    }
  };

  // ============= 2. RENDER FUNCTION =============

  return (
    <div className="space-y-6">
      {/* Policy Rule Alert */}
      <Alert className="bg-yellow-50 text-yellow-800 border-yellow-200">
        <Info className="h-4 w-4" />
        <AlertTitle>Policy Rule</AlertTitle>
        <AlertDescription className="text-xs">
          Creating a new policy will automatically set its status to 'Inactive'.
          You must enable it via the Policy Edit modal afterwards.
        </AlertDescription>
      </Alert>

      {/* Target Part ID (Read-only) */}
      <div className="space-y-2">
        <Label>Target Part ID</Label>
        <Input
          value={initialPartId || "N/A"}
          disabled
          readOnly
          className="bg-muted/50"
        />
      </div>

      <div className="space-y-4">
        {/* Policy Name */}
        <div className="space-y-2">
          <Label>Policy Name *</Label>
          <Input
            placeholder="e.g., Extended 3 Year Warranty"
            value={formData.policyName}
            onChange={(e) => handleChange("policyName", e.target.value)}
            disabled={isSubmitting}
          />
        </div>

        <div className="grid grid-cols-2 gap-4">
          {/* Available Year */}
          <div className="space-y-2">
            <Label>Available Year *</Label>
            <Input
              type="number"
              min="1"
              placeholder="e.g., 3 (years)"
              value={formData.availableYear}
              onChange={(e) => handleChange("availableYear", e.target.value)}
              disabled={isSubmitting}
            />
          </div>

          {/* Kilometer (Formatted Input) */}
          <div className="space-y-2">
            <Label>Kilometer *</Label>
            <Input
              type="text"
              placeholder="e.g., 100,000 (km)"
              value={formattedKilometer}
              onChange={handleKilometerChange}
              disabled={isSubmitting}
            />
          </div>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex justify-end gap-2">
        <Button variant="outline" onClick={onCancel} disabled={isSubmitting}>
          Cancel
        </Button>

        <Button
          onClick={handleSubmit}
          disabled={
            isSubmitting ||
            !initialPartId ||
            !formData.policyName ||
            !formData.availableYear ||
            !formattedKilometer
          }
        >
          {isSubmitting ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin mr-2" /> Creating...
            </>
          ) : (
            "Create Policy"
          )}
        </Button>
      </div>
    </div>
  );
}
