// FE/src/components/admin/AdPoliCreate.jsx

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Info } from "lucide-react"

/**
 * @function formatNumber
 * @param {number|string} num - The number value to format.
 * @returns {string} The formatted number string (e.g., "4,000,000").
 */
const formatNumber = (num) => {
  if (!num || isNaN(Number(num))) return "";
  // Using "en-US" locale for comma separation
  return Number(num).toLocaleString("en-US"); 
};

const INITIAL_FORM_DATA = {
  policyName: "",
  availableYear: "",
  kilometer: "",
};

/**
 * @component
 * @description Form component for creating a new Policy for a specific Part.
 * @param {string} initialPartId - The ID of the part the policy belongs to.
 * @param {function} onSubmit - Handler to submit the new policy data.
 * @param {function} onCancel - Handler to close the modal.
 */
export default function CreatePolicyForm({ initialPartId, onSubmit, onCancel }) {
  const [formData, setFormData] = useState(INITIAL_FORM_DATA);
  const [formattedKilometer, setFormattedKilometer] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  /**
     * @function handleChange
     * @param {string} field - The key of the field to update.
     * @param {*} value - The new value for the field.
     * @description Generic handler to update form data state.
     */
  const handleChange = (field, value) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };
    
  /**
     * @function handleKilometerChange
     * @param {Object} e - Event object from the input field.
     * @description Handles input for the Kilometer field, formats the display value,
     * and saves the raw numeric string to formData.
     */
  const handleKilometerChange = (e) => {
    const inputStr = e.target.value;
    const rawNumberStr = inputStr.replace(/[^0-9]/g, "");
    const numericValue = rawNumberStr ? parseInt(rawNumberStr, 10) : "";
    // Save raw numeric string to formData
    handleChange("kilometer", String(numericValue));
    // Save formatted value for display
    setFormattedKilometer(formatNumber(numericValue));
  };

  /**
     * @function handleSubmit
     * @description Validates the form, converts necessary fields to numbers, and calls the parent onSubmit handler.
     */
  const handleSubmit = async () => {
    if (
      !initialPartId ||
      !(formData.policyName && formData.availableYear && formData.kilometer)
    ) {
      alert("Please fill in all required fields.");
      return;
    }
    
    setIsSubmitting(true);
    
    const policyDataToSend = {
      // policyId is generated by the API
      policyName: formData.policyName,
      availableYear: Number(formData.availableYear),
      kilometer: Number(formData.kilometer),
      isEnable: true, // Defaulting new policy to Active
      partId: initialPartId,
    };

    try {
        await onSubmit(policyDataToSend);
        setFormData(INITIAL_FORM_DATA);
        setFormattedKilometer("");
    } catch (error) {
        // Error handling is delegated to the parent component (AdminPartsPolicy.jsx)
    } finally {
        setIsSubmitting(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Policy Rule Alert */}
      <Alert className="bg-yellow-50 text-yellow-800 border-yellow-200">
        <Info className="h-4 w-4" />
        <AlertTitle>Policy Rule</AlertTitle>
        <AlertDescription className="text-xs">
          Creating a new policy will automatically set it to **Active**.
          Ensure only one policy is active per part if required by business logic.
        </AlertDescription>
      </Alert>
      
      {/* Target Part ID (Read-only) */}
      <div className="space-y-2">
        <Label>Target Part ID</Label>
        <Input 
          value={initialPartId || "N/A"} 
          disabled 
          readOnly 
          className="bg-muted/50"
        />
      </div>

      <div className="space-y-4">
        <div className="space-y-2">
          <Label>Policy Name *</Label>
          <Input
            placeholder="e.g., Extended 3 Year Warranty"
            value={formData.policyName}
            onChange={(e) => handleChange("policyName", e.target.value)}
            disabled={isSubmitting}
          />
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label>Available Year *</Label>
            <Input
              type="number"
              placeholder="e.g., 3 (years)"
              value={formData.availableYear}
              onChange={(e) => handleChange("availableYear", e.target.value)}
              disabled={isSubmitting}
          />
          </div>

          <div className="space-y-2">
            <Label>Kilometer *</Label>
            <Input
              type="text" 
              placeholder="e.g., 100,000 (km)"
              value={formattedKilometer}
              onChange={handleKilometerChange}
              disabled={isSubmitting}
            />
          </div>
        </div>
      </div>

      <div className="flex justify-end gap-2">
        <Button variant="outline" onClick={onCancel} disabled={isSubmitting}>
          Cancel
        </Button>
        <Button onClick={handleSubmit} disabled={isSubmitting || !initialPartId}>
          {isSubmitting ? "Creating..." : "Create Policy"}
        </Button>
      </div>
    </div>
  )
}