// FE/src/lib/provinces.js

export const provinces = {
  "Ha Noi": ["Ba Dinh", "Cau Giay", "Dong Da", "Thanh Xuan", "Hoang Mai", "Ha Dong", "Long Bien"],
  "TP Ho Chi Minh": ["Quan 1", "Quan 3", "Quan 5", "Tan Binh", "Go Vap", "Binh Thanh", "Thu Duc"],
  "Da Nang": ["Hai Chau", "Thanh Khe", "Son Tra", "Ngu Hanh Son", "Lien Chieu", "Cam Le"],
  "Hai Phong": ["Hong Bang", "Ngo Quyen", "Le Chan", "Kien An", "Hai An"],
  "Can Tho": ["Ninh Kieu", "Binh Thuy", "Cai Rang", "O Mon", "Thot Not"],
  "An Giang": ["Long Xuyen", "Chau Doc", "Tan Chau", "Chau Phu", "Tri Ton"],
  "Ba Ria - Vung Tau": ["Vung Tau", "Ba Ria", "Long Dien", "Dat Do", "Tan Thanh"],
  "Bac Giang": ["Bac Giang", "Yen Dung", "Lang Giang", "Tan Yen", "Hiep Hoa"],
  "Bac Kan": ["Bac Kan", "Ba Be", "Ngan Son", "Cho Don", "Cho Moi"],
  "Bac Lieu": ["Bac Lieu", "Hoa Binh", "Dong Hai", "Gia Rai", "Phuoc Long"],
  "Bac Ninh": ["Bac Ninh", "Tien Du", "Tu Son", "Que Vo", "Yen Phong"],
  "Ben Tre": ["Ben Tre", "Ba Tri", "Binh Dai", "Cho Lach", "Mo Cay"],
  "Binh Dinh": ["Quy Nhon", "An Nhon", "Tay Son", "Phu Cat", "Hoai Nhon"],
  "Binh Duong": ["Thu Dau Mot", "Di An", "Tan Uyen", "Ben Cat", "Thuan An"],
  "Binh Phuoc": ["Dong Xoai", "Phuoc Long", "Binh Long", "Chon Thanh", "Dong Phu"],
  "Binh Thuan": ["Phan Thiet", "La Gi", "Bac Binh", "Ham Thuan Bac", "Tuy Phong"],
  "Ca Mau": ["Ca Mau", "Dam Doi", "Nam Can", "Ngoc Hien", "Tran Van Thoi"],
  "Cao Bang": ["Cao Bang", "Bao Lam", "Bao Lac", "Ha Quang", "Nguyen Binh"],
  "Dak Lak": ["Buon Ma Thuot", "Buon Ho", "Ea Kar", "Krong Ana", "Krong Pak"],
  "Dak Nong": ["Gia Nghia", "Dak Mil", "Dak Rlap", "Cu Jut", "Krong No"],
  "Dien Bien": ["Dien Bien Phu", "Muong Lay", "Muong Ang", "Tuan Giao", "Dien Bien"],
  "Dong Nai": ["Bien Hoa", "Long Khanh", "Trang Bom", "Long Thanh", "Nhon Trach"],
  "Dong Thap": ["Cao Lanh", "Sa Dec", "Hong Ngu", "Lap Vo", "Thanh Binh"],
  "Gia Lai": ["Pleiku", "An Khe", "Ayun Pa", "Chu Prong", "Mang Yang"],
  "Ha Giang": ["Ha Giang", "Dong Van", "Quan Ba", "Yen Minh", "Hoang Su Phi"],
  "Ha Nam": ["Phu Ly", "Duy Tien", "Kim Bang", "Ly Nhan", "Binh Luc"],
  "Ha Tinh": ["Ha Tinh", "Hong Linh", "Cam Xuyen", "Ky Anh", "Thach Ha"],
  "Hai Duong": ["Hai Duong", "Chi Linh", "Nam Sach", "Cam Giang", "Thanh Mien"],
  "Hau Giang": ["Vi Thanh", "Nga Bay", "Chau Thanh", "Phung Hiep", "Long My"],
  "Hoa Binh": ["Hoa Binh", "Luong Son", "Mai Chau", "Tan Lac", "Lac Son"],
  "Hung Yen": ["Hung Yen", "My Hao", "Van Lam", "Khoai Chau", "Kim Dong"],
  "Khanh Hoa": ["Nha Trang", "Cam Ranh", "Ninh Hoa", "Van Ninh", "Dien Khanh"],
  "Kien Giang": ["Rach Gia", "Ha Tien", "Phu Quoc", "Chau Thanh", "Go Quao"],
  "Kon Tum": ["Kon Tum", "Dak Ha", "Ngoc Hoi", "Dak To", "Kon Plong"],
  "Lai Chau": ["Lai Chau", "Muong Te", "Phong Tho", "Tam Duong", "Than Uyen"]
};
